name: journeycraft
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  flutter_swiper_view: ^1.1.8
  flutter_picker: ^2.1.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  adaptive_theme: ^3.7.0
  animated_text_kit: ^4.2.3
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - keys.env
    - lib/assets/animations/Globe.gif
    - lib/assets/animations/Passport.gif
    - lib/assets/animations/Plane.gif
    - lib/assets/animations/Robot.gif
    - lib/assets/google_logo.png
    - lib/assets/codes.json
