name: journeycraft
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - keys.env
    - lib/assets/animations/Globe.gif
    - lib/assets/animations/Passport.gif
    - lib/assets/animations/Plane.gif
    - lib/assets/animations/Robot.gif
    - lib/assets/google_logo.png
